# Generated by Django 4.2.23 on 2025-07-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantprofile',
            options={'ordering': ['restaurant'], 'verbose_name': 'رستوران', 'verbose_name_plural': 'رستوران\u200cها'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم رستوران'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/', verbose_name='لگو'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='restaurants.restaurant', verbose_name='رستوران'),
        ),
    ]
