# Generated by Django 4.2.23 on 2025-07-08 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_alter_restaurantprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL, verbose_name='مدیر'),
        ),
    ]
