# Generated by Django 4.2.23 on 2025-07-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantprofile_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='manager',
        ),
    ]
